name: story-producer-chatbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: noochmedia/story-producer-chatbot
  build_command: pip install -r requirements.txt
  run_command: gunicorn --config gunicorn_config.py wsgi:application
  environment_slug: python
  instance_size_slug: basic-xxs
  instance_count: 1
  env:
    - key: FLASK_ENV
      scope: RUN_TIME
      value: "production"
    - key: PORT
      scope: RUN_TIME
      value: "8000"
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
    - path: /