name: story-producer-chatbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  build_command: pip install -r requirements.txt
  run_command: gunicorn --config gunicorn_config.py wsgi:application
  environment_slug: python
  env:
    - key: MISTRAL_API_URL
      value: "http://162.243.42.76"
    - key: MISTRAL_API_KEY
      value: "L2Nisrbtg4s+KBTgK5fgKRDW+bcI/lx4a8QZ7Odyv7PCO2LWA"
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
    - path: /