name: story-producer-chatbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: noochmedia/story-producer-chatbot
  build_command: pip install -r requirements.txt
  run_command: gunicorn --config gunicorn_config.py wsgi:application
  environment_slug: python
  env_specific_configs:
    python_version: "3.11"
  env:
    - key: FLASK_ENV
      scope: RUN_TIME
      type: GENERAL
      value: "production"
    - key: PORT
      scope: RUN_TIME
      type: GENERAL
      value: "8000"
    # Note: The following should be set in Digital Ocean's dashboard, not in this file
    # - key: MISTRAL_API_URL
    # - key: MISTRAL_API_KEY
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 5
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
    - path: /