name: story-producer-chatbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: noochmedia/story-producer-chatbot
  build_command: pip install -r requirements.txt
  run_command: cd /workspace && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level debug wsgi:application
  environment_slug: python
  instance_size_slug: basic-xxs
  instance_count: 1
  env:
    - key: FLASK_ENV
      value: "production"
    - key: PORT
      value: "8000"
    - key: PYTHON_VERSION
      value: "3.11"
    - key: MISTRAL_API_URL
      value: "http://162.243.42.76"
    - key: MISTRAL_API_KEY
      value: "L2Nisrbtg4s+KBTgK5fgKRDW+bcI/lx4a8QZ7Odyv7PCO2LWA"
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  routes:
    - path: /