name: story-producer-chatbot
services:
- name: web
  source_dir: /
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: noochmedia/story-producer-chatbot
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
    - path: /
  envs:
    - key: FLASK_ENV
      value: "production"
    - key: PYTHONPATH
      value: "/app"
    - key: PORT
      value: "8000"
    - key: MISTRAL_API_URL
      value: "http://162.243.42.76"
    - key: MISTRAL_API_KEY
      value: "L2Nisrbtg4s+KBTgK5fgKRDW+bcI/lx4a8QZ7Odyv7PCO2LWA"