[theme]
primaryColor = "#3498db"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"
font = "sans-serif"

[server]
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
